Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2020-10, with the labels that each got.

#652 Fix add! and addeq! for GF
  src/julia/GF.jl
  test/julia/GFElem-test.jl
Labels: bugfix

#656 Map doc: fix few typos
  docs/src/map.md
Labels: doc

#648 follow the Random API for Poly and Integers via RandomExtensions.make
  Project.toml
  src/AbstractAlgebra.jl
  src/Generic.jl
  src/generic/Fraction.jl
  src/generic/LaurentPoly.jl
  src/generic/LaurentSeries.jl
  src/generic/MPoly.jl
  src/generic/Matrix.jl
  src/generic/MatrixAlgebra.jl
  src/generic/Module.jl
  src/generic/NCPoly.jl
  src/generic/Poly.jl
  src/generic/PuiseuxSeries.jl
  src/generic/RelSeries.jl
  src/generic/Residue.jl
  src/generic/ResidueField.jl
  src/julia/Float.jl
  src/julia/Integer.jl
  src/julia/Rational.jl
  test/generic/Fraction-test.jl
  test/generic/LaurentPoly-test.jl
  test/generic/LaurentSeries-test.jl
  test/generic/MPoly-test.jl
  test/generic/Matrix-test.jl
  test/generic/MatrixAlgebra-test.jl
  test/generic/Module-test.jl
  test/generic/NCPoly-test.jl
  test/generic/Poly-test.jl
  test/generic/PuiseuxSeries-test.jl
  test/generic/RelSeries-test.jl
  test/generic/Residue-test.jl
  test/generic/ResidueField-test.jl
  test/julia/Floats-test.jl
  test/julia/Integers-test.jl
  test/julia/Rationals-test.jl
  test/runtests.jl
Labels: breaking

#662 fix #467, "docstring odditites
  src/AbstractAlgebra.jl
  src/Factor.jl
  src/NCRings.jl
  src/Rings.jl
  src/algorithms/LaurentPoly.jl
  src/generic/AbsSeries.jl
  src/generic/DirectSum.jl
  src/generic/Fraction.jl
  src/generic/FreeModule.jl
  src/generic/GenericTypes.jl
  src/generic/InvariantFactorDecomposition.jl
  src/generic/LaurentPoly.jl
  src/generic/LaurentSeries.jl
  src/generic/MPoly.jl
  src/generic/Matrix.jl
  src/generic/MatrixAlgebra.jl
  src/generic/Module.jl
  src/generic/ModuleHomomorphism.jl
  src/generic/NCPoly.jl
  src/generic/PermGroups.jl
  src/generic/Poly.jl
  src/generic/PuiseuxSeries.jl
  src/generic/QuotientModule.jl
  src/generic/RelSeries.jl
  src/generic/Residue.jl
  src/generic/ResidueField.jl
  src/generic/SparsePoly.jl
  src/generic/Submodule.jl
  src/generic/YoungTabs.jl
  src/julia/GF.jl
  src/julia/Integer.jl
  src/julia/Rational.jl
Labels: doc

#670 enable rand for matrix spaces beyond Generic.MatSpaceElem
  src/generic/Matrix.jl
  test/AbstractAlgebra-test.jl
  test/generic/Matrix-test.jl
  test/runtests.jl
Labels: bugfix

#671 fix reproducibility of rand for MPoly, and add reproducibility tests
  src/generic/MPoly.jl
  test/generic/Fraction-test.jl
  test/generic/LaurentPoly-test.jl
  test/generic/LaurentSeries-test.jl
  test/generic/MPoly-test.jl
  test/generic/Matrix-test.jl
  test/generic/MatrixAlgebra-test.jl
  test/generic/Module-test.jl
  test/generic/NCPoly-test.jl
  test/generic/Poly-test.jl
  test/generic/PuiseuxSeries-test.jl
  test/generic/RelSeries-test.jl
  test/generic/Residue-test.jl
  test/generic/ResidueField-test.jl
  test/julia/Floats-test.jl
  test/julia/GFElem-test.jl
  test/julia/Integers-test.jl
  test/julia/Rationals-test.jl
  test/runtests.jl
Labels: bugfix
