Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2021-01, with the labels that each got.

#709 fix warnings when building the documentation (fix #707)
  docs/src/fraction.md
  docs/src/matrix.md
  docs/src/module_homomorphism.md
  docs/src/perm.md
  docs/src/puiseux.md
  docs/src/residue.md
  docs/src/series.md
Labels: doc

#715 Retire legacy printer
  docs/src/matrix_spaces.md
  docs/src/ncrings.md
  docs/src/rings.md
  src/AbstractAlgebra.jl
  src/Factor.jl
  src/Generic.jl
  src/PrettyPrinting.jl
  src/algorithms/LaurentPoly.jl
  src/generic/Fraction.jl
  src/generic/LaurentSeries.jl
  src/generic/MPoly.jl
  src/generic/MatrixAlgebra.jl
  src/generic/NCPoly.jl
  src/generic/Poly.jl
  src/generic/PuiseuxSeries.jl
  src/generic/RelSeries.jl
  src/generic/Residue.jl
  src/generic/ResidueField.jl
  src/generic/SparsePoly.jl
  src/julia/Float.jl
  src/julia/GF.jl
  src/julia/Integer.jl
  src/julia/Rational.jl
  test/AbstractAlgebra-test.jl
  test/Factor-test.jl
  test/PrettyPrinting-test.jl
  test/Rings-test.jl
  test/generic/Fraction-test.jl
  test/generic/MPoly-test.jl
  test/generic/Poly-test.jl
  test/generic/PuiseuxSeries-test.jl
  test/generic/ResidueField-test.jl
  test/generic/SparsePoly-test.jl
  test/julia/Floats-test.jl
  test/julia/GFElem-test.jl
  todo.txt
Labels: breaking

#540 implement some array interfaces for matrices
  docs/src/matrix.md
  src/generic/Matrix.jl
  test/generic/Matrix-test.jl
Labels: enhancement, matrices

#721 add linear indexing for matrices which have only one row or column
  src/generic/Matrix.jl
  test/generic/Matrix-test.jl
Labels: matrices
