Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2024-04, with the labels that each got.

#1647 Add julia 1.11-nightly to CI matrix
  .github/workflows/CI.yml
Labels: test

#1670 Remove `vcat(::MatElem, ::MatElem)` and `hcat(::MatElem, ::MatElem)`
  src/Matrix.jl
  test/Matrix-test.jl
Labels: breaking

#1680 Print base rings terse and starting with lowercase
  docs/src/direct_sum.md
  docs/src/free_associative_algebra.md
  docs/src/function_field.md
  docs/src/module.md
  docs/src/module_homomorphism.md
  docs/src/mpolynomial.md
  docs/src/ncpolynomial.md
  docs/src/quotient_module.md
  docs/src/submodule.md
  docs/src/total_fraction.md
  src/NCPoly.jl
  src/generic/DirectSum.jl
  src/generic/FreeModule.jl
  src/generic/FunctionField.jl
  src/generic/InvariantFactorDecomposition.jl
  src/generic/MPoly.jl
  src/generic/Misc/Localization.jl
  src/generic/QuotientModule.jl
  src/generic/SparsePoly.jl
  src/generic/Submodule.jl
  src/generic/TotalFraction.jl
Labels: breaks printing

#1675 move code from `Oscar.jl/experimental/GModule/Misc.jl` here
  src/Map.jl
  src/Matrix.jl
  src/Module.jl
  src/exports.jl
  src/generic/DirectSum.jl
  src/generic/FreeModule.jl
  src/generic/Map.jl
  src/generic/Misc/Poly.jl
  src/generic/ModuleHomomorphism.jl
  src/generic/exports.jl
Labels: breaking

#1684 Breaking changes for linear solving
  src/Solve.jl
Labels: breaking

#1671 Use `@show_name`, `@show_special` for all (?) parent show methods
  src/AbsMSeries.jl
  src/Fraction.jl
  src/FreeAssAlgebra.jl
  src/LaurentMPoly.jl
  src/MPoly.jl
  src/Map.jl
  src/MatRing.jl
  src/NCPoly.jl
  src/Poly.jl
  src/RelSeries.jl
  src/Residue.jl
  src/ResidueField.jl
  src/algorithms/LaurentPoly.jl
  src/generic/DirectSum.jl
  src/generic/FunctionField.jl
  src/generic/InvariantFactorDecomposition.jl
  src/generic/LaurentSeries.jl
  src/generic/Misc/Localization.jl
  src/generic/PuiseuxSeries.jl
  src/generic/QuotientModule.jl
  src/generic/RationalFunctionField.jl
  src/generic/SparsePoly.jl
  src/generic/TotalFraction.jl
  src/generic/UnivPoly.jl
  src/generic/imports.jl
  src/julia/GF.jl
Labels: breaks printing

#1688 Change things that waited for a breaking release
  src/AbstractAlgebra.jl
  src/Aliases.jl
Labels: breaking

#1692 Fixes for SparsePolyRing
  src/exports.jl
  src/generic/GenericTypes.jl
  src/generic/SparsePoly.jl
  test/generic/SparsePoly-test.jl
Labels: breaking
