Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2025-07, with the labels that each got.

#2114 Add `rank` method for `DirectSumModule`
  src/generic/DirectSum.jl
  src/generic/QuotientModule.jl
  test/generic/DirectSum-test.jl
  test/generic/QuotientModule-test.jl
Labels: enhancement, release notes: use title

#2121 Bump julia compat to 1.10
  .github/workflows/CI.yml
  .github/workflows/hecke.yml
  .github/workflows/oscar.yml
  .github/workflows/singular.yml
  Project.toml
  docs/src/index.md
Labels: breaking, release notes: use title

#2119 Clean up obsolete `VERSION` checks
  src/Attributes.jl
  src/Matrix.jl
  test/Attributes-test.jl
  test/generic/MPoly-test.jl
  test/generic/Matrix-test.jl
  test/misc-test.jl
  test/runtests.jl
Labels: release notes: not needed

#2092 Add `fraction_field_type` and define `fraction_field` method for fields
  src/Fraction.jl
  src/exports.jl
  src/generic/FunctionField.jl
  src/generic/RationalFunctionField.jl
Labels: enhancement, release notes: use title
