Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2025-01, with the labels that each got.

#1973 Enable multivariate factorization in characteristic 0 (at least over coefficient rings for which univariate factorization is implemented)
  src/MPoly.jl
Labels: enhancement, release notes: use title

#1971 Remove `content(::PolyRingElem{<:FieldElem})` method which always returns 1, as this disagrees with the definition of `content` over some fields
  src/Poly.jl
Labels: release notes: use title

#1970 Add `content(::UnivPoly)`, fix potentially wrong result in `content(::MatrixElem)`, optimize a few other `content` methods
  src/MPoly.jl
  src/Matrix.jl
  src/Poly.jl
  src/UnivPoly.jl
  test/generic/UnivPoly-test.jl
Labels: enhancement, release notes: use title

#1954 Move conformance tests to a package extension
  Project.toml
  docs/src/ring_interface.md
  ext/TestExt/Groups-conformance-tests.jl
  ext/TestExt/Mutating-ops.jl
  ext/TestExt/Rings-conformance-tests.jl
  ext/TestExt/TestExt.jl
  src/AbstractAlgebra.jl
  src/ConformanceTests.jl
  src/Deprecations.jl
  src/FreeAssociativeAlgebra.jl
  src/LaurentMPoly.jl
  src/MPoly.jl
  src/MatRing.jl
  src/Matrix.jl
  src/Poly.jl
  src/RelSeries.jl
  src/algorithms/FinField.jl
  src/exports.jl
  src/generic/AbsMSeries.jl
  src/generic/FactoredFraction.jl
  src/generic/FunctionField.jl
  src/generic/LaurentPoly.jl
  src/generic/LaurentSeries.jl
  src/generic/PuiseuxSeries.jl
  src/generic/RationalFunctionField.jl
  src/generic/Residue.jl
  src/generic/UnivPoly.jl
  src/imports.jl
  src/julia/Float.jl
  src/julia/Integer.jl
  src/julia/Rational.jl
  test/AbstractAlgebra-test.jl
  test/Groups-conformance-tests.jl
  test/Rings-conformance-tests.jl
  test/conformance-tests.jl
  test/generic/AbsMSeries-test.jl
  test/generic/AbsSeries-test.jl
  test/generic/FactoredFraction-test.jl
  test/generic/FreeAssociativeAlgebra-test.jl
  test/generic/FunctionField-test.jl
  test/generic/LaurentMPoly-test.jl
  test/generic/LaurentPoly-test.jl
  test/generic/LaurentSeries-test.jl
  test/generic/MPoly-test.jl
  test/generic/PermGroupAPI-test.jl
  test/generic/Poly-test.jl
  test/generic/PuiseuxSeries-test.jl
  test/generic/RationalFunctionField-test.jl
  test/generic/RelSeries-test.jl
  test/generic/Residue-test.jl
  test/generic/UnivPoly-test.jl
  test/julia/Floats-test.jl
  test/julia/GFElem-test.jl
  test/julia/Integers-test.jl
  test/julia/Rationals-test.jl
Labels: enhancement, release notes: to be added

#1975 Improve documentation of `add_verbosity_scope`
  docs/src/assertions.md
  src/Assertions.jl
Labels: release notes: use title
