Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2025-09, with the labels that each got.

#2134 Cf/perm gmodule
  src/Matrix.jl
  src/Module.jl
  src/ModuleHomomorphism.jl
  src/Poly.jl
  src/generic/DirectSum.jl
Labels: enhancement, release notes: not needed

#2132 Add `fraction_field_type` and define `fraction_field` method for fields
  src/Fraction.jl
  src/exports.jl
  src/generic/FunctionField.jl
  src/generic/RationalFunctionField.jl
Labels: enhancement, breaking, release notes: use title

#2145 Add `identity_map` to excluded imports
  src/AbstractAlgebra.jl
Labels: breaking

#2150 feat: do not print `1` in factorizations
  src/Factor.jl
Labels: breaking

#2171 Add is_attribute_storing and is_attribute_storing_type
  docs/src/misc.md
  src/Attributes.jl
  src/KnownProperties.jl
  src/PrettyPrinting.jl
  src/exports.jl
  test/Attributes-test.jl
Labels: enhancement
