Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2025-05, with the labels that each got.

#2065 Fix `swap_cols!` for `Matrix{T}`
  src/julia/Matrix.jl
Labels: bug, release notes: use title

#2069 Add `canonical_unit(x::FieldElement) = x`, and stop some `canonical_unit` methods from returning non-units when the input is zero
  src/Fields.jl
  src/Fraction.jl
  src/NumFields.jl
  src/ResidueField.jl
  src/generic/RationalFunctionField.jl
  src/julia/Float.jl
  src/julia/GF.jl
  src/julia/Rational.jl
Labels: release notes: use title

#2066 Fix a typo in `var_index` docstring
  src/MPoly.jl
Labels: release notes: not needed

#2068 Remove bad generic sqrt method
  src/Rings.jl
Labels: release notes: use title

#2067 Update CHANGELOG.md
  CHANGELOG.md
Labels: release notes: not needed

#2080 chore: bump version to 0.45.0-DEV
  Project.toml
Labels: release notes: not needed

#2002 Breaking changes to the conformance test setup
  src/Deprecations.jl
  test/Groups-conformance-tests.jl
  test/Rings-conformance-tests.jl
  test/conformance-tests.jl
Labels: breaking, release notes: to be added

#2006 Make `RationalFunctionFieldElem` immutable
  src/generic/GenericTypes.jl
  src/generic/RationalFunctionField.jl
Labels: breaking, release notes: use title

#2081 Move `Infinity.jl` from Nemo
  src/AbstractAlgebra.jl
  src/Infinity.jl
  src/exports.jl
  test/AbstractAlgebra-test.jl
  test/Infinity-test.jl
Labels: breaking

#2003 Remove `ignore_kwargs` option from `@attr`
  src/Deprecations.jl
Labels: breaking, release notes: use title

#2082 Move parts of Oscar's `MoveToAbstractAlgebra.jl` over
  src/Matrix.jl
  src/exports.jl
  src/generic/LaurentPoly.jl
  src/generic/RationalFunctionField.jl
  test/generic/Matrix-test.jl
Labels: breaking

#2085 doctests: add verbose output, disable Matrix-Strassen doctest
  .github/workflows/CI.yml
  docs/documenter_helpers.jl
  src/Matrix-Strassen.jl
Labels: release notes: not needed

#2086 Add `coefficient_ring_type`
  src/FreeAssociativeAlgebra.jl
  src/MPoly.jl
  src/NCPoly.jl
  src/Poly.jl
  src/exports.jl
  src/fundamental_interface.jl
  src/generic/LaurentMPoly.jl
  src/generic/LaurentPoly.jl
  src/generic/UnivPoly.jl
  src/generic/imports.jl
  test/generic/FreeAssociativeAlgebra-test.jl
  test/generic/LaurentMPoly-test.jl
  test/generic/LaurentPoly-test.jl
  test/generic/MPoly-test.jl
  test/generic/NCPoly-test.jl
  test/generic/Poly-test.jl
  test/generic/UnivPoly-test.jl
Labels: enhancement, release notes: use title

#2091 Alias `ispositive`/`isnegative` in recent enough julia versions
  src/Aliases.jl
  src/julia/Float.jl
Labels: release notes: use title

#2096 Don't use `inv` and `inv!` in ring conformance tests
  ext/TestExt/Rings-conformance-tests.jl
Labels: release notes: not needed

#2105 Fix Singular downstream tests
  .github/workflows/singular.yml
Labels: release notes: not needed
