Repository Nemocas/AbstractAlgebra.jl, pull requests merged in 2025-03, with the labels that each got.

#2018 More intuitive polynomial evaluation, e.g. `f(y=3)` to substitute 3 for the variable named `y` in the polynomial `f`
  src/generic/UnivPoly.jl
  test/generic/MPoly-test.jl
  test/generic/UnivPoly-test.jl
Labels: enhancement, release notes: use title

#2013 Some tweaks to evaluate methods
  src/AbsSeries.jl
  src/MPoly.jl
  src/Poly.jl
  src/RelSeries.jl
  src/generic/AbsMSeries.jl
  src/generic/GenericTypes.jl
  src/generic/LaurentSeries.jl
  src/generic/MPoly.jl
  src/generic/UnivPoly.jl
  test/generic/MPoly-test.jl
Labels: release notes: not needed

#2022 Fix some references in the Linear Solving docs
  docs/src/linear_solving.md
  src/Solve.jl
Labels: doc, release notes: not needed

#2025 chore: Bump to 0.44.9
  Project.toml
Labels: release notes: not needed

#2024 Replace Val-dispatch by if-else in Generic.MPoly
  src/Deprecations.jl
  src/generic/MPoly.jl
Labels: release notes: not needed

#2028 Improvements for multivariate and universal polynomials
  src/MPoly.jl
  src/generic/MPoly.jl
  src/generic/UnivPoly.jl
  test/generic/UnivPoly-test.jl
Labels: release notes: not needed

#2037 Remove broken `is_unit` and `is_nilpotent` for `NCPolyRingElem`
  docs/src/ncpolynomial.md
  src/MPoly.jl
  src/NCPoly.jl
  src/Poly.jl
  test/generic/NCPoly-test.jl
Labels: release notes: use title

#2044 chore: Bump version to 0.44.11
  Project.toml
Labels: release notes: not needed
